version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
    open-pull-requests-limit: 8
    labels:
      - dependencies
      - security
    groups:
      production-patch-minor:
        dependency-type: production
        update-types:
          - "patch"
          - "minor"
      dev-dependencies:
        dependency-type: development
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
    labels:
      - dependencies
      - github-actions
